### ISSUE TITLE
Minecraft Class Bindings

### ISSUE THREAD

**Issue by conorthedev** [PufferfishModLoader/PufferfishModLoader#2]
This is one of the larger to-do's. This is going to bind *most* Minecraft classes (i.e. ChatComponentText, EntityPlayer*) to a PML variant allowing us to keep the syntax the same, providing almost seamless transitions between Minecraft versions for mods.

**Comment by dreamhopping** [comment]
Moved to [here](https://github.com/PufferfishModLoader/PufferfishAPI/issues/2)
